name: sakani
description: "Sakani - تطبيق سكني وعرض الشقق"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  http: ^1.2.2
  provider: ^6.1.2

  cupertino_icons: ^1.0.8
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  crypto: ^3.0.6
  encrypt: ^5.0.3
  intl: ^0.20.2
  google_fonts: ^6.2.1
  flutter_bloc: ^9.1.1
  get_it: ^9.3.0
  equatable: ^3.0.0
  shimmer: ^4.0.0
  local_auth: ^3.0.2
  shared_preferences: ^2.5.5
  pdf: ^3.13.1
  audioplayers: ^6.8.1
  share_plus: ^10.1.4
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/