import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:sakani/features/settings/presentation/providers/locale_provider.dart';

class AppLocalizations {
  final String lang;

  AppLocalizations(this.lang);

  static AppLocalizations of(String lang) => AppLocalizations(lang);

  static const Map<String, Map<String, String>> _localized = {
    'ar': {
      // App & General
      'appName': 'سكني',
      'appTagline': 'تأجير الشقق الفاخرة المعتمدة',
      'language': 'اللغة',
      'arabic': 'العربية',
      'english': 'English',
      'darkMode': 'الوضع الداكن',
      'lightMode': 'الوضع الفاتح',
      'cancel': 'إلغاء',
      'save': 'حفظ',
      'confirm': 'تأكيد',
      'currency': 'ج.م',
      'perMonth': 'ج.م / شهرياً',
      'perDay': 'ج.م / يومياً',

      // Navigation & Tabs
      'home': 'الرئيسية',
      'explore': 'استكشاف',
      'wishlist': 'المفضلة',
      'favorites': 'المفضلة',
      'myBookings': 'حجوزاتي',
      'chats': 'المحادثات',
      'myAccount': 'حسابي',
      'settings': 'الإعدادات',

      // Auth
      'login': 'تسجيل الدخول',
      'register': 'إنشاء حساب',
      'logout': 'تسجيل خروج',
      'email': 'البريد الإلكتروني',
      'password': 'كلمة المرور',
      'fullName': 'الاسم الكامل',
      'phone': 'رقم الجوال',
      'accountType': 'نوع الحساب',
      'tenant': 'مستأجر',
      'owner': 'مالك عقار',
      'noAccount': 'ليس لديك حساب؟ إنشاء حساب جديد',
      'hasAccount': 'لديك حساب بالفعل؟ تسجيل الدخول',
      'emailRequired': 'البريد الإلكتروني مطلوب',
      'passwordRequired': 'كلمة المرور يجب أن تكون 6 أحرف على الأقل',
      'nameRequired': 'الاسم مطلوب',
      'phoneRequired': 'رقم جوال صحيح مطلوب',
      'welcome': 'مرحباً!',
      'welcomeBack': 'مرحباً بعودتك!',

      // Apartment Search & Details
      'findApartment': 'ابحث عن شقتك المثالية',
      'searchPlaceholder': 'ابحث بالمدينة أو الحي أو المنطقة...',
      'allCities': 'كل المدن',
      'cairo': 'القاهرة',
      'giza': 'الجيزة',
      'alexandria': 'الإسكندرية',
      'tagamoa': 'التجمع الخامس',
      'zayed': 'الشيخ زايد',
      'northCoast': 'الساحل الشمالي',
      'apartmentDetails': 'تفاصيل الشقة',
      'apartmentInfo': 'معلومات الشقة',
      'bookNow': 'حجز الآن',
      'instantBook': 'حجز فوري',
      'noApartments': 'لا توجد شقق متاحة حالياً',
      'bedrooms': 'غرف النوم',
      'bathrooms': 'الحمامات',
      'area': 'المساحة (م²)',
      'maxGuests': 'أقصى ضيوف',
      'amenities': 'المرافق والخدمات',
      'description': 'الوصف والبيانات',
      'location': 'الموقع الجغرافي',
      'city': 'المدينة',
      'address': 'العنوان',
      'ownerName': 'المالك',
      'contactPhone': 'هاتف التواصل',

      // Rental Types
      'daily': 'يومي',
      'monthly': 'شهري',
      'yearly': 'سنوي',
      'rentalType': 'نوع الإيجار',

      // Booking & Payment
      'bookingTitle': 'حجز الشقة',
      'bookingDate': 'تاريخ الحجز',
      'from': 'من',
      'to': 'إلى',
      'duration': 'مدة الإقامة',
      'days': 'يوم',
      'months': 'شهر',
      'guests': 'عدد الضيوف',
      'guest': 'ضيف',
      'baseRent': 'المبلغ الأساسي للإيجار',
      'platformCommission': 'عمولة المنصة',
      'fairDeposit': 'تأمين مالي عادل',
      'totalDue': 'الإجمالي المطلوب دفعه',
      'paymentMethod': 'طريقة الدفع والحساب الوسيط',
      'escrowBadge': 'ضمان مالي شامل (Escrow Safe Pay)',
      'escrowDescription': 'أموالك محمية بحساب وسيط، ولا يتم تحويلها إلى المالك إلا بعد استلام الشقة والتأكد من مطابقتها للمواصفات.',
      'walletPay': 'محفظة سكني الرقمية',
      'cardPay': 'بطاقة بنكية (Visa / MasterCard / Meeza)',
      'vodafonePay': 'محافظ المحمول وإنستاباي (InstaPay)',
      'fawryPay': 'فوري باي (FawryPay)',
      'confirmBooking': 'تأكيد الحجز',
      'bookingSuccess': 'تم إرسال طلب الحجز بنجاح والمبلغ محمي بحساب الضمان 🛡️',
      'insufficientBalance': 'رصيد المحفظة غير كافٍ. يرجى الشحن أو اختيار وسيلة دفع أخرى.',

      // E-Contract & Signature
      'eContract': 'عقد الإيجار الإلكتروني الموحد',
      'digitalSignature': 'التوقيع الرقمي باليد',
      'signHere': 'وقّع هنا بإصبعك ✍️',
      'clearSignature': 'مسح التوقيع',
      'saveSignature': 'اعتماد التوقيع',
      'agreeToTerms': 'أوافق على كافة الشروط والأحكام الخاصة بالعقد الموحد',
      'contractAuthenticated': 'توثيق واعتماد العقد رسمياً',
      'previewContract': 'معاينة وتوقيع عقد الإيجار الإلكتروني ✍️',

      // AI Assistant & Calculator
      'aiAssistant': 'المساعد العقاري الذكي (AI)',
      'aiRentEstimator': 'حاسبة تسعير الإيجار العادل',
      'chatWithAi': 'محادثة وبحث ذكي',
      'aiThinking': 'جاري التفكير وتحليل الشقق المتاحة...',
      'suggestedPrice': 'القيمة الإيجارية المقترحة بالذكاء الاصطناعي',

      // Trust & Reviews
      'trustScore': 'مؤشر الثقة',
      'verifiedUser': 'طرف موثوق ومعتمد',
      'addReview': 'إضافة تقييم جديد',
      'submitReview': 'إرسال التقييم',

      // Notifications
      'notifications': 'الإشعارات',
      'markAllAsRead': 'تحديد الكل كمقروء',
      'noNotifications': 'لا توجد إشعارات جديدة حالياً',

      // Amenities
      'furnished': 'مفروشة بالكامل',
      'airConditioned': 'مكيفة بالكامل',
      'wifi': 'إنترنت فائق السرعة',
      'elevator': 'مصعد كهربائي',
      'parking': 'موقف سيارات خاص',
      'security': 'أمن وحراسة 24/7',
      'balcony': 'شرفة وإطلالة مميزة',
      'pool': 'حمام سباحة',
      'gym': 'صالة رياضية / جيم',
      'kitchen': 'مطبخ متكامل الأجهزة',

      // Filter & General
      'all': 'الكل',
      'seeAll': 'عرض الكل',
      'search': 'بحث',
      'filter': 'تصفية',
      'noResults': 'لا توجد شقق مطابقة لخيارات البحث',
      'startDate': 'تاريخ الوصول',
      'endDate': 'تاريخ المغادرة',
      'nights': 'ليالي',
      'night': 'ليلة',
      'changeLanguage': 'تغيير اللغة',
      'languageChanged': 'تم تغيير لغة التطبيق بنجاح',
      'wallet': 'المحفظة الرقمية',
      'currentBalance': 'الرصيد المتاح',
      'topUp': 'شحن الرصيد',
      'history': 'سجل المعاملات',
      'contracts': 'العقود الإلكترونية',
      'support': 'الدعم الفني والمساعدة',
      'terms': 'الشروط والأحكام',
      'privacy': 'سياسة الخصوصية',
      'aboutUs': 'عن منصة سكني',
      'close': 'إغلاق',
      'retry': 'إعادة المحاولة',
      'profile': 'الملف الشخصي',
      'editProfile': 'تعديل البيانات',
      'securitySettings': 'إعدادات الأمان',
      'notificationsSettings': 'إعدادات الإشعارات',
      'appearance': 'المظهر والسمة',

      // Owner Dashboard
      'ownerDashboard': 'لوحة التحكم',
      'myProperties': 'عقاراتي',
      'manageBookings': 'إدارة الحجوزات',
      'addApartment': 'إضافة عقار جديد',
      'viewMyProperties': 'عرض عقاراتي',
      'recentBookingRequests': 'أحدث طلبات الحجز',
      'realizedEarnings': 'أرباح المحفظة المحققة',
      'pendingEscrow': 'أرباح قيد التسوية (حجوزات نشطة):',
      'totalProperties': 'إجمالي العقارات',
      'occupancyRate': 'نسبة الإشغال',
      'availableForRent': 'متاح للحجز',
      'available': 'متاح',
      'unavailable': 'غير متاح',
      'occupied': 'مشغول',
      'occupiedFrom': 'مشغول من',
      'until': 'حتى',
      'availableForInstantBooking': 'متاح للحجز الفوري والتأجير',
      'editPrice': 'تعديل السعر',
      'savePrice': 'حفظ السعر',
      'editRentPrice': 'تعديل سعر الإيجار',
      'enterNewMonthlyPrice': 'أدخل السعر الشهري الجديد لعقار: ',
      'monthlyRentPrice': 'السعر الشهري (ج.م)',
      'activeBookingsCount': 'حجوزات جارية',
      'daysRemaining': 'متبقي %s يوم',
      'deleteProperty': 'حذف العقار',
      'deleteConfirm': 'هل أنت متأكد من حذف "%s"؟ لا يمكن التراجع عن هذا الإجراء.',
      'myWallet': 'محفظتي',
      'filterAll': 'الكل',
      'filterPending': 'قيد الانتظار',
      'filterActive': 'نشط',
      'filterAccepted': 'مقبول',
      'filterCompleted': 'مكتمل',
      'filterCancelled': 'ملغي',
      'noBookingsCategory': 'لا توجد حجوزات في هذا التصنيف',
      'noBookingsCategorySub': 'اختر تصنيفاً آخر أو انتظر طلبات جديدة',
      'noBookingsYet': 'لا توجد طلبات حجز بعد',
      'noBookingsSubtitle': 'ستظهر طلبات المستأجرين هنا فور إرسالها',
      'noPropertiesYet': 'لم تقم بإضافة عقارات بعد',
      'noPropertiesSubtitle': 'اضغط على زر "إضافة عقار" لنشر شقتك السكنية الأولى والبدء في استقبال المستأجرين',
      'addPropertyNow': 'إضافة عقار الآن',
      'bookingConfirmedSuccess': 'تم تأكيد حجز "%s" بنجاح! تم حجز العقار وإيداع %s ج.م في محفظتك.',
      'propertyPriceUpdated': 'تم تحديث سعر العقار إلى %s ج.م شهرياً بنجاح',

      // Settings & Profile
      'appearanceAndLanguage': 'المظهر واللغة',
      'darkModeActive': 'الوضع الداكن مفعّل',
      'lightModeActive': 'الوضع الفاتح مفعّل',
      'currentLanguage': 'اللغة الحالية: العربية',
      'securityAndAlerts': 'الأمان والتنبيهات',
      'changePassword': 'تغيير كلمة المرور',
      'changePasswordDesc': 'حماية وتأمين الحساب',
      'currentPassword': 'كلمة المرور الحالية',
      'newPassword': 'كلمة المرور الجديدة',
      'passwordUpdatedSuccess': 'تم تحديث كلمة المرور بنجاح 🌟',
      'biometricLogin': 'تسجيل الدخول بالبصمة / Face ID',
      'biometricLoginDesc': 'تفعيل الدخول السريع عبر البصمة الحيوية',
      'biometricAuthPrompt': 'يرجى التحقق من البصمة لتفعيل الدخول السريع',
      'biometricEnabled': 'تم تفعيل تسجيل الدخول بالبصمة بنجاح 🌟',
      'biometricDisabled': 'تم تعطيل تسجيل الدخول بالبصمة',
      'appNotifications': 'إشعارات التطبيق',
      'appNotificationsDesc': 'تنبيهات الحجوزات والرسائل الجديدة',
      'notifSettingsUpdated': 'تم تحديث إعدادات الإشعارات',
      'supportAndInfo': 'الدعم والمعلومات',
      'liveSupport': 'الدعم الفني المباشر (Live Support 🎧)',
      'liveSupportDesc': 'محادثة حية فورية ومتابعة مع موظفي الشيفت',
      'termsAndPolicies': 'الشروط والأحكام والسياسات',
      'termsAndPoliciesDesc': 'شروط الاستخدام وسياسة الخصوصية',
      'termsDialogContent': 'تطبيق سكني يضمن حقوق المستأجر والمالك وفقاً للقوانين المصرية ومعايير الأمان المالي. جميع الحجوزات مشمولة بضمان استرداد الأموال وتوثيق الهوية الرقمي.',
      'aboutSakani': 'عن تطبيق سكني',
      'version': 'الإصدار 1.0.0 (النسخة الفاخرة)',
      'logoutDesc': 'تسجيل الخروج من الحساب الحالي',
      'logoutConfirmTitle': 'تسجيل الخروج',
      'logoutConfirmMessage': 'هل أنت متأكد من رغبتك في تسجيل الخروج من تطبيق سكني؟',
      'walletBalance': 'رصيد المحفظة',
      'kycVerification': 'توثيق الهوية (KYC)',
      'fullyVerified': 'موثق بالكامل 🌟',
      'notVerified': 'غير موثق',
      'verifiedOwner': '🏢 مالك عقارات موثق',
      'verifiedTenant': '👤 مستأجر موثق',
      'profileVerifiedDesc': 'البيانات الشخصية مكتملة ومؤكدة',
      'welcomeToSakani': 'مرحباً بك في سكني',
      'welcomeToSakaniSub': 'سجل دخولك للاستمتاع بجميع المزايا',
      'changePhoto': 'تغيير الصورة الشخصية',
      'takePhoto': 'التقاط صورة بالكاميرا',
      'chooseFromGallery': 'اختيار من ألبوم الصور',
      'photoUpdatedSuccess': 'تم تحديث الصورة الشخصية بنجاح 🌟',
      'editProfileTitle': 'تعديل البيانات الشخصية',
      'profileUpdatedSuccess': 'تم تحديث البيانات الشخصية بنجاح 🌟',
      'updateError': 'حدث خطأ أثناء التحديث',

      // Add Apartment
      'addNewApartment': 'إضافة شقة جديدة',
      'propertyInfo': 'معلومات الشقة',
      'propertyTitle': 'عنوان الشقة',
      'propertyTitleRequired': 'العنوان مطلوب',
      'propertyDescription': 'الوصف',
      'cityGovernorate': 'المدينة / المحافظة',
      'cityPlaceholder': 'مثال: القاهرة، الجيزة، الإسكندرية...',
      'cityRequired': 'يرجى كتابة اسم المدينة',
      'detailedAddress': 'العنوان التفصيلي / الحي والشارع',
      'detailedAddressRequired': 'العنوان التفصيلي مطلوب',
      'phoneContact': 'رقم الجوال للتواصل',
      'propertySpecs': 'التفاصيل والمواصفات',
      'bedroomsCount': 'غرف النوم',
      'bathroomsCount': 'الحمامات',
      'maxGuestsCount': 'أقصى ضيوف',
      'areaSqm': 'المساحة (م²)',
      'propertyImagesMin': 'صور الشقة (3 صور على الأقل)',
      'minImagesRequired': 'يجب إضافة 3 صور على الأقل للشقة',
      'selectRentTypeMin': 'يجب اختيار نوع إيجار واحد على الأقل',
      'rentTypeAndPrices': 'نوع الإيجار والأسعار',
      'dailyPrice': 'السعر اليومي',
      'dailyPriceRequired': 'السعر اليومي مطلوب',
      'monthlyPrice': 'السعر الشهري',
      'monthlyPriceRequired': 'السعر الشهري مطلوب',
      'yearlyPrice': 'السعر السنوي',
      'yearlyPriceRequired': 'السعر السنوي مطلوب',
      'securityDeposit': 'مبلغ التأمين',
      'amenitiesAndFacilities': 'الخدمات والمرافق',
      'submitAddProperty': 'إضافة الشقة',
      'propertyAddedSuccess': 'تم إضافة الشقة بنجاح!',

      // Apartment Details
      'aboutThisHome': 'عن هذا السكن',
      'availableForRentNow': 'متاحة للحجز الآن',
      'currentlyBooked': 'محجوزة حالياً',
      'reviewsCount': '(%s تقييم)',
      'verifiedHost': 'مالك معتمد وموثق',
      'chatWithHost': 'محادثة المالك',
      'loginToChat': 'يرجى تسجيل الدخول أولاً للمحادثة',
      'linkCopied': 'تم نسخ رابط الشقة للمشاركة',
      'addedToFav': 'تمت الإضافة للمفضلة',
      'removedFromFav': 'تمت الإزالة من المفضلة',
    },
    'en': {
      // App & General
      'appName': 'Sakani',
      'appTagline': 'Luxury Verified Apartments Rental',
      'language': 'Language',
      'arabic': 'العربية',
      'english': 'English',
      'darkMode': 'Dark Mode',
      'lightMode': 'Light Mode',
      'cancel': 'Cancel',
      'save': 'Save',
      'confirm': 'Confirm',
      'currency': 'EGP',
      'perMonth': 'EGP / Month',
      'perDay': 'EGP / Day',

      // Navigation & Tabs
      'home': 'Home',
      'explore': 'Explore',
      'wishlist': 'Wishlist',
      'favorites': 'Favorites',
      'myBookings': 'My Bookings',
      'chats': 'Chats',
      'myAccount': 'My Account',
      'settings': 'Settings',

      // Auth
      'login': 'Login',
      'register': 'Create Account',
      'logout': 'Logout',
      'email': 'Email',
      'password': 'Password',
      'fullName': 'Full Name',
      'phone': 'Phone Number',
      'accountType': 'Account Type',
      'tenant': 'Tenant',
      'owner': 'Property Owner',
      'noAccount': "Don't have an account? Sign Up",
      'hasAccount': 'Already have an account? Login',
      'emailRequired': 'Email is required',
      'passwordRequired': 'Password must be at least 6 characters',
      'nameRequired': 'Full name is required',
      'phoneRequired': 'Valid phone number is required',
      'welcome': 'Welcome!',
      'welcomeBack': 'Welcome back!',

      // Apartment Search & Details
      'findApartment': 'Find your dream apartment',
      'searchPlaceholder': 'Search by city, district or area...',
      'allCities': 'All Cities',
      'cairo': 'Cairo',
      'giza': 'Giza',
      'alexandria': 'Alexandria',
      'tagamoa': 'New Cairo (Tagamoa)',
      'zayed': 'Sheikh Zayed',
      'northCoast': 'North Coast',
      'apartmentDetails': 'Apartment Details',
      'apartmentInfo': 'Apartment Info',
      'bookNow': 'Book Now',
      'instantBook': 'Instant Booking',
      'noApartments': 'No apartments available currently',
      'bedrooms': 'Bedrooms',
      'bathrooms': 'Bathrooms',
      'area': 'Area (m²)',
      'maxGuests': 'Max Guests',
      'amenities': 'Amenities & Facilities',
      'description': 'Description & Overview',
      'location': 'Location',
      'city': 'City',
      'address': 'Address',
      'ownerName': 'Owner',
      'contactPhone': 'Contact Phone',

      // Rental Types
      'daily': 'Daily',
      'monthly': 'Monthly',
      'yearly': 'Yearly',
      'rentalType': 'Rental Type',

      // Booking & Payment
      'bookingTitle': 'Book Apartment',
      'bookingDate': 'Booking Dates',
      'from': 'From',
      'to': 'To',
      'duration': 'Stay Duration',
      'days': 'Days',
      'months': 'Months',
      'guests': 'Number of Guests',
      'guest': 'Guest',
      'baseRent': 'Base Rental Amount',
      'platformCommission': 'Platform Commission',
      'fairDeposit': 'Fair Security Deposit',
      'totalDue': 'Total Payable Amount',
      'paymentMethod': 'Payment Method & Escrow',
      'escrowBadge': 'Escrow Safe Pay Guarantee',
      'escrowDescription': 'Your funds are held securely in escrow and only released to the landlord after inspection and check-in confirmation.',
      'walletPay': 'Sakani Digital Wallet',
      'cardPay': 'Credit/Debit Card (Visa/Mastercard/Meeza)',
      'vodafonePay': 'Mobile Wallets & InstaPay',
      'fawryPay': 'FawryPay (Cash Reference Code)',
      'confirmBooking': 'Confirm Booking',
      'bookingSuccess': 'Booking request submitted successfully with Escrow protection 🛡️',
      'insufficientBalance': 'Insufficient wallet balance. Please top up or choose another payment method.',

      // E-Contract & Signature
      'eContract': 'Unified Digital Tenancy Contract',
      'digitalSignature': 'Digital Hand Signature',
      'signHere': 'Sign here with your finger ✍️',
      'clearSignature': 'Clear Signature',
      'saveSignature': 'Apply Signature',
      'agreeToTerms': 'I agree to all tenancy contract terms and conditions',
      'contractAuthenticated': 'Officially Authenticate Contract',
      'previewContract': 'Preview & Sign E-Tenancy Contract ✍️',

      // AI Assistant & Calculator
      'aiAssistant': 'AI Property Assistant',
      'aiRentEstimator': 'Fair Rent Estimator',
      'chatWithAi': 'Smart Search & Chat',
      'aiThinking': 'Analyzing available apartments...',
      'suggestedPrice': 'AI Suggested Fair Monthly Rent',

      // Trust & Reviews
      'trustScore': 'Trust Score',
      'verifiedUser': 'Verified & Trusted User',
      'addReview': 'Add New Review',
      'submitReview': 'Submit Review',

      // Notifications
      'notifications': 'Notifications',
      'markAllAsRead': 'Mark all as read',
      'noNotifications': 'No new notifications currently',

      // Map View
      'interactiveMap': 'Interactive Apartments Map',
      'filterByCity': 'Filter by Area',

      // Amenities
      'furnished': 'Fully Furnished',
      'airConditioned': 'Air Conditioned',
      'wifi': 'High-Speed Wi-Fi',
      'elevator': 'Elevator',
      'parking': 'Private Parking',
      'security': '24/7 Security',
      'balcony': 'Scenic Balcony',
      'pool': 'Swimming Pool',
      'gym': 'Gym / Fitness',
      'kitchen': 'Equipped Kitchen',

      // Filter & General
      'all': 'All',
      'seeAll': 'See All',
      'search': 'Search',
      'filter': 'Filter',
      'noResults': 'No apartments match your search criteria',
      'startDate': 'Check-in Date',
      'endDate': 'Check-out Date',
      'nights': 'nights',
      'night': 'night',
      'changeLanguage': 'Change Language',
      'languageChanged': 'App language updated successfully',
      'wallet': 'Digital Wallet',
      'currentBalance': 'Available Balance',
      'topUp': 'Top Up Balance',
      'history': 'Transaction History',
      'contracts': 'E-Contracts',
      'support': 'Customer Support',
      'terms': 'Terms & Conditions',
      'privacy': 'Privacy Policy',
      'aboutUs': 'About Sakani',
      'close': 'Close',
      'retry': 'Retry',
      'profile': 'Profile',
      'editProfile': 'Edit Profile',
      'securitySettings': 'Security Settings',
      'notificationsSettings': 'Notification Settings',
      'appearance': 'Appearance & Theme',

      // Owner Dashboard
      'ownerDashboard': 'Dashboard',
      'myProperties': 'My Properties',
      'manageBookings': 'Manage Bookings',
      'addApartment': 'Add New Property',
      'viewMyProperties': 'View My Properties',
      'recentBookingRequests': 'Recent Booking Requests',
      'realizedEarnings': 'Realized Wallet Earnings',
      'pendingEscrow': 'Pending Escrow (Active Bookings):',
      'totalProperties': 'Total Properties',
      'occupancyRate': 'Occupancy Rate',
      'availableForRent': 'Available for Rent',
      'available': 'Available',
      'unavailable': 'Unavailable',
      'occupied': 'Occupied',
      'occupiedFrom': 'Occupied from',
      'until': 'until',
      'availableForInstantBooking': 'Available for Instant Booking',
      'editPrice': 'Edit Price',
      'savePrice': 'Save Price',
      'editRentPrice': 'Edit Rental Price',
      'enterNewMonthlyPrice': 'Enter new monthly rent for: ',
      'monthlyRentPrice': 'Monthly Rent (EGP)',
      'activeBookingsCount': 'active bookings',
      'daysRemaining': '%s days left',
      'deleteProperty': 'Delete Property',
      'deleteConfirm': 'Are you sure you want to delete "%s"? This action cannot be undone.',
      'myWallet': 'My Wallet',
      'filterAll': 'All',
      'filterPending': 'Pending',
      'filterActive': 'Active',
      'filterAccepted': 'Accepted',
      'filterCompleted': 'Completed',
      'filterCancelled': 'Cancelled',
      'noBookingsCategory': 'No bookings in this category',
      'noBookingsCategorySub': 'Choose another category or wait for new requests',
      'noBookingsYet': 'No booking requests yet',
      'noBookingsSubtitle': 'Tenant booking requests will appear here as soon as they are submitted',
      'noPropertiesYet': "You haven't added any properties yet",
      'noPropertiesSubtitle': 'Tap "Add Property" to publish your first property and start receiving tenants',
      'addPropertyNow': 'Add Property Now',
      'bookingConfirmedSuccess': 'Booking for "%s" confirmed! Property reserved and %s EGP deposited into your wallet.',
      'propertyPriceUpdated': 'Property price successfully updated to %s EGP/month',

      // Settings & Profile
      'appearanceAndLanguage': 'Appearance & Language',
      'darkModeActive': 'Dark Mode Enabled',
      'lightModeActive': 'Light Mode Enabled',
      'currentLanguage': 'Current: English',
      'securityAndAlerts': 'Security & Alerts',
      'changePassword': 'Change Password',
      'changePasswordDesc': 'Protect and secure your account',
      'currentPassword': 'Current Password',
      'newPassword': 'New Password',
      'passwordUpdatedSuccess': 'Password updated successfully 🌟',
      'biometricLogin': 'Biometric Login / Face ID',
      'biometricLoginDesc': 'Enable fast login via biometrics',
      'biometricAuthPrompt': 'Please authenticate to enable biometric login',
      'biometricEnabled': 'Biometric login enabled successfully 🌟',
      'biometricDisabled': 'Biometric login disabled',
      'appNotifications': 'App Notifications',
      'appNotificationsDesc': 'Booking alerts and new messages',
      'notifSettingsUpdated': 'Notification settings updated',
      'supportAndInfo': 'Support & Information',
      'liveSupport': 'Live Technical Support 🎧',
      'liveSupportDesc': 'Instant live chat with support team',
      'termsAndPolicies': 'Terms, Conditions & Policies',
      'termsAndPoliciesDesc': 'Terms of use and privacy policy',
      'termsDialogContent': 'Sakani guarantees tenant and owner rights in accordance with Egyptian legal standards and escrow financial security. All bookings are backed by money-back guarantee and digital KYC identity verification.',
      'aboutSakani': 'About Sakani App',
      'version': 'Version 1.0.0 (Luxury Edition)',
      'logoutDesc': 'Sign out of current account',
      'logoutConfirmTitle': 'Sign Out',
      'logoutConfirmMessage': 'Are you sure you want to sign out of Sakani?',
      'walletBalance': 'Wallet Balance',
      'kycVerification': 'Identity Verification (KYC)',
      'fullyVerified': 'Fully Verified 🌟',
      'notVerified': 'Not Verified',
      'verifiedOwner': '🏢 Verified Property Owner',
      'verifiedTenant': '👤 Verified Tenant',
      'profileVerifiedDesc': 'Profile information verified and confirmed',
      'welcomeToSakani': 'Welcome to Sakani',
      'welcomeToSakaniSub': 'Sign in to enjoy all exclusive features',
      'changePhoto': 'Change Profile Picture',
      'takePhoto': 'Take photo with camera',
      'chooseFromGallery': 'Choose from photo gallery',
      'photoUpdatedSuccess': 'Profile photo updated successfully 🌟',
      'editProfileTitle': 'Edit Profile Information',
      'profileUpdatedSuccess': 'Profile updated successfully 🌟',
      'updateError': 'Error occurred while updating',

      // Add Apartment
      'addNewApartment': 'Add New Property',
      'propertyInfo': 'Property Information',
      'propertyTitle': 'Property Title',
      'propertyTitleRequired': 'Title is required',
      'propertyDescription': 'Description',
      'cityGovernorate': 'City / Governorate',
      'cityPlaceholder': 'e.g. Cairo, Giza, Alexandria...',
      'cityRequired': 'Please enter city name',
      'detailedAddress': 'Detailed Address / District & Street',
      'detailedAddressRequired': 'Detailed address is required',
      'phoneContact': 'Contact Phone Number',
      'propertySpecs': 'Specifications & Details',
      'bedroomsCount': 'Bedrooms',
      'bathroomsCount': 'Bathrooms',
      'maxGuestsCount': 'Max Guests',
      'areaSqm': 'Area (sqm)',
      'propertyImagesMin': 'Property Photos (at least 3 photos)',
      'minImagesRequired': 'Please add at least 3 photos for the property',
      'selectRentTypeMin': 'Please select at least one rental type',
      'rentTypeAndPrices': 'Rental Types & Pricing',
      'dailyPrice': 'Daily Price',
      'dailyPriceRequired': 'Daily price is required',
      'monthlyPrice': 'Monthly Price',
      'monthlyPriceRequired': 'Monthly price is required',
      'yearlyPrice': 'Yearly Price',
      'yearlyPriceRequired': 'Yearly price is required',
      'securityDeposit': 'Security Deposit',
      'amenitiesAndFacilities': 'Amenities & Facilities',
      'submitAddProperty': 'Add Property',
      'propertyAddedSuccess': 'Property added successfully!',

      // Apartment Details
      'aboutThisHome': 'About This Home',
      'availableForRentNow': 'Available for Booking Now',
      'currentlyBooked': 'Currently Booked',
      'reviewsCount': '(%s reviews)',
      'verifiedHost': 'Certified & Verified Owner',
      'chatWithHost': 'Chat with Host',
      'loginToChat': 'Please sign in first to chat',
      'linkCopied': 'Property link copied to clipboard',
      'addedToFav': 'Added to favorites',
      'removedFromFav': 'Removed from favorites',
    },
  };

  static const LocalizationsDelegate<AppLocalizations> delegate = _AppLocalizationsDelegate();

  String tr(String key, [List<String>? args]) {
    final map = _localized[lang] ?? _localized['ar']!;
    var text = map[key] ?? key;
    if (args != null) {
      for (final arg in args) {
        text = text.replaceFirst('%s', arg);
      }
    }
    return text;
  }
}

class _AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['ar', 'en'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale.languageCode);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}

extension StringTranslate on String {
  String tr(String lang, [List<String>? args]) {
    return AppLocalizations(lang).tr(this, args);
  }
}

extension BuildContextLocalization on BuildContext {
  String tr(String key, [List<String>? args]) {
    final lang = watch<LocaleProvider>().lang;
    return AppLocalizations(lang).tr(key, args);
  }

  bool get isArabic => watch<LocaleProvider>().isArabic;
  String get currentLang => watch<LocaleProvider>().lang;
}

