class AppLocalizations {
  final String lang;

  AppLocalizations(this.lang);

  static AppLocalizations of(String lang) => AppLocalizations(lang);

  static const Map<String, Map<String, String>> _localized = {
    'ar': {
      'appName': 'سكني',
      'appTagline': 'تأجير الشقق الفاخرة',
      'login': 'تسجيل الدخول',
      'register': 'إنشاء حساب',
      'logout': 'تسجيل خروج',
      'email': 'البريد الإلكتروني',
      'password': 'كلمة المرور',
      'fullName': 'الاسم الكامل',
      'phone': 'رقم الجوال',
      'accountType': 'نوع الحساب',
      'tenant': 'مستأجر',
      'owner': 'مالك',
      'noAccount': 'ليس لديك حساب؟ إنشاء حساب جديد',
      'hasAccount': 'لديك حساب بالفعل؟ تسجيل الدخول',
      'emailRequired': 'البريد الإلكتروني مطلوب',
      'passwordRequired': 'كلمة المرور يجب أن تكون 6 أحرف على الأقل',
      'nameRequired': 'الاسم مطلوب',
      'phoneRequired': 'رقم جوال صحيح مطلوب',
      'darkMode': 'الوضع الداكن',
      'lightMode': 'الوضع الفاتح',
      'language': 'اللغة',
      'arabic': 'العربية',
      'english': 'English',
      'home': 'الرئيسية',
      'explore': 'استكشاف',
      'wishlist': 'المفضلة',
      'favorites': 'المفضلة',
      'myBookings': 'حجوزاتي',
      'chats': 'المحادثات',
      'myAccount': 'حسابي',
      'noApartments': 'لا توجد شقق متاحة حالياً',
      'noBookings': 'لا توجد حجوزات',
      'noChats': 'لا توجد محادثات',
      'welcome': 'مرحباً!',
      'findApartment': 'ابحث عن شقتك المثالية',
      'apartmentDetails': 'تفاصيل الشقة',
      'bookNow': 'حجز الآن',
      'chat': 'محادثة',
      'sendMessage': 'اكتب رسالة...',
      'startChat': 'ابدأ المحادثة',
      'bookingConfirmed': 'تم إرسال طلب الحجز بنجاح',
      'addApartment': 'إضافة شقة جديدة',
      'apartmentAdded': 'تم إضافة الشقة بنجاح',
      'dashboard': 'لوحة التحكم',
      'welcomeBack': 'مرحباً بعودتك!',
      'manageApartments': 'إدارة شققك وحجوزاتك',
      'apartments': 'الشقق',
      'bookings': 'الحجوزات',
      'active': 'نشط',
      'totalEarnings': 'إجمالي الأرباح',
      'commission': 'عمولة سكني',
      'recentBookings': 'الحجوزات الحديثة',
      'pending': 'قيد الانتظار',
      'accepted': 'مقبول',
      'cancelled': 'ملغي',
      'completed': 'مكتمل',
      'accept': 'قبول',
      'reject': 'رفض',
      'available': 'متاحة',
      'notAvailable': 'غير متاحة',
      'daily': 'يومي',
      'monthly': 'شهري',
      'yearly': 'سنوي',
      'description': 'الوصف',
      'amenities': 'الخدمات والمرافق',
      'deposit': 'معلومات الإيداع',
      'securityDeposit': 'تأمين: %s جنية (قابل للاسترداد)',
      'price': 'السعر',
      'total': 'المجموع',
      'bookingDate': 'تاريخ الحجز',
      'from': 'من',
      'to': 'إلى',
      'guests': 'الضيوف',
      'guest': 'ضيف',
      'confirmBooking': 'تأكيد الحجز',
      'apartmentInfo': 'معلومات الشقة',
      'details': 'التفاصيل',
      'prices': 'الأسعار',
      'city': 'المدينة',
      'address': 'العنوان',
      'contactPhone': 'رقم الجوال للتواصل',
      'bedrooms': 'غرف النوم',
      'bathrooms': 'الحمامات',
      'area': 'المساحة (م²)',
      'maxGuests': 'أقصى ضيوف',
      'submit': 'إضافة الشقة',
      'cancel': 'إلغاء',
      'ownerName': 'المالك',
    },
    'en': {
      'appName': 'Sakani',
      'appTagline': 'Luxury Apartment Rental',
      'login': 'Login',
      'register': 'Create Account',
      'logout': 'Logout',
      'email': 'Email',
      'password': 'Password',
      'fullName': 'Full Name',
      'phone': 'Phone Number',
      'accountType': 'Account Type',
      'tenant': 'Tenant',
      'owner': 'Owner',
      'noAccount': "Don't have an account? Register",
      'hasAccount': 'Already have an account? Login',
      'emailRequired': 'Email is required',
      'passwordRequired': 'Password must be at least 6 characters',
      'nameRequired': 'Name is required',
      'phoneRequired': 'Valid phone number is required',
      'darkMode': 'Dark Mode',
      'lightMode': 'Light Mode',
      'language': 'Language',
      'arabic': 'العربية',
      'english': 'English',
      'home': 'Home',
      'explore': 'Explore',
      'wishlist': 'Wishlist',
      'favorites': 'Favorites',
      'myBookings': 'My Bookings',
      'chats': 'Chats',
      'myAccount': 'My Account',
      'noApartments': 'No apartments available',
      'noBookings': 'No bookings found',
      'noChats': 'No conversations yet',
      'welcome': 'Welcome!',
      'findApartment': 'Find your perfect apartment',
      'apartmentDetails': 'Apartment Details',
      'bookNow': 'Book Now',
      'chat': 'Chat',
      'sendMessage': 'Type a message...',
      'startChat': 'Start a conversation',
      'bookingConfirmed': 'Booking request sent successfully',
      'addApartment': 'Add New Apartment',
      'apartmentAdded': 'Apartment added successfully',
      'dashboard': 'Dashboard',
      'welcomeBack': 'Welcome back!',
      'manageApartments': 'Manage your apartments & bookings',
      'apartments': 'Apartments',
      'bookings': 'Bookings',
      'active': 'Active',
      'totalEarnings': 'Total Earnings',
      'commission': 'Sakani Commission',
      'recentBookings': 'Recent Bookings',
      'pending': 'Pending',
      'accepted': 'Accepted',
      'cancelled': 'Cancelled',
      'completed': 'Completed',
      'accept': 'Accept',
      'reject': 'Reject',
      'available': 'Available',
      'notAvailable': 'Not Available',
      'daily': 'Daily',
      'monthly': 'Monthly',
      'yearly': 'Yearly',
      'description': 'Description',
      'amenities': 'Amenities',
      'deposit': 'Deposit Info',
      'securityDeposit': 'Deposit: %s SAR (refundable)',
      'price': 'Price',
      'total': 'Total',
      'bookingDate': 'Booking Date',
      'from': 'From',
      'to': 'To',
      'guests': 'Guests',
      'guest': 'Guest',
      'confirmBooking': 'Confirm Booking',
      'apartmentInfo': 'Apartment Info',
      'details': 'Details',
      'prices': 'Prices',
      'city': 'City',
      'address': 'Address',
      'contactPhone': 'Contact Phone',
      'bedrooms': 'Bedrooms',
      'bathrooms': 'Bathrooms',
      'area': 'Area (m²)',
      'maxGuests': 'Max Guests',
      'submit': 'Add Apartment',
      'cancel': 'Cancel',
      'ownerName': 'Owner',
    },
  };

  String tr(String key, [List<String>? args]) {
    final map = _localized[lang] ?? _localized['ar']!;
    var text = map[key] ?? key;
    if (args != null) {
      for (final arg in args) {
        text = text.replaceFirst('%s', arg);
      }
    }
    return text;
  }
}

extension StringTranslate on String {
  String tr(String lang, [List<String>? args]) {
    return AppLocalizations(lang).tr(this, args);
  }
}
